name: Terraform

defaults:
  run:
    working-directory: ./src/gcp/cloudfunctions

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - src/gcp/cloudfunctions/**

jobs:
  terraform:
    name: Deploy Cloud Functions v2
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/<project-id>/locations/global/workloadIdentityPools/zdh-workflow-wi-pool/providers/github'
        service_account: zdh-workflow-action@<project-name>.iam.gserviceaccount.com

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Zip Function Code
      run: |
        cd sample_code
        zip -r sample_code.zip *

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      run: terraform apply -auto-approve
